server:
  port: 8093

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 动态线程池管理配置
dynamic:
  thread:
    pool:
      config:
        # 状态；true = 开启、false 关闭
        enabled: true
        # redis host
        host: 192.168.150.128
        # redis port
        port: 6379
        password: 123321
      notify:
        enabled: true
        userPlatform:
          - DingDing
          - FeiShu
        accessToken:
          dingDing: 008578d130993c11667719e366a680ac0dca08944400cabd0ed595ffff41f46b
          feiShu:
        secret:
          dingDing: SEC1e99cfee6f77ae1febd25a86a71905ca4cf2f4e53877707f115c4f60fd46ecb0
          feiShu:
        report:
          cron: "*/20 * * * * ?"
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    prometheus:
      enabled: true

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
